name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make

      - name: Configure
        run: make configure

      - name: Build
        run: make build

      - name: Test
        run: make test
